In [3]:
import pandas as pd
import numpy as np

In [4]:
data=pd.read_csv('data1.csv')
data

A     B     C     D
0  10.0  20.0  30.0  40.0
1   1.0   2.0   NaN   4.0
2   5.0   6.0   NaN   8.0
3  11.0   NaN  13.0  14.0

In [5]:
data.tail(2)


A    B     C     D
2   5.0  6.0   NaN   8.0
3  11.0  NaN  13.0  14.0

In [6]:
data.head(2)

A     B     C     D
0  10.0  20.0  30.0  40.0
1   1.0   2.0   NaN   4.0

In [7]:
data.values

array([[10., 20., 30., 40.],
       [ 1.,  2., nan,  4.],
       [ 5.,  6., nan,  8.],
       [11., nan, 13., 14.]])

In [8]:
data.to_numpy()

array([[10., 20., 30., 40.],
       [ 1.,  2., nan,  4.],
       [ 5.,  6., nan,  8.],
       [11., nan, 13., 14.]])

In [9]:
data.isnull().sum()

A    0
B    1
C    2
D    0
dtype: int64

In [10]:
from io import StringIO
csv_data='''A,B,C,D
1,2,3,
5,6,,7
8,9,,
'''

In [11]:
df1=pd.read_csv(StringIO(csv_data))

In [12]:
df1

A  B    C    D
0  1  2  3.0  NaN
1  5  6  NaN  7.0
2  8  9  NaN  NaN

In [13]:
data.dropna(axis=1)#column

A     D
0  10.0  40.0
1   1.0   4.0
2   5.0   8.0
3  11.0  14.0

In [14]:
data.dropna(axis=0)#row

A     B     C     D
0  10.0  20.0  30.0  40.0

In [15]:
data.dropna(axis=1,subset=[1,1])

A     B     D
0  10.0  20.0  40.0
1   1.0   2.0   4.0
2   5.0   6.0   8.0
3  11.0   NaN  14.0

In [16]:
data.dropna(how='any')

A     B     C     D
0  10.0  20.0  30.0  40.0

In [17]:
data.dropna(how='all')

A     B     C     D
0  10.0  20.0  30.0  40.0
1   1.0   2.0   NaN   4.0
2   5.0   6.0   NaN   8.0
3  11.0   NaN  13.0  14.0

In [18]:
data.dropna(thresh=4,axis=0)

A     B     C     D
0  10.0  20.0  30.0  40.0

In [19]:
from sklearn.impute import SimpleImputer

In [20]:
s=SimpleImputer(strategy='mean',missing_values=np.nan)

In [21]:
s.fit_transform(data)

array([[10.        , 20.        , 30.        , 40.        ],
       [ 1.        ,  2.        , 21.5       ,  4.        ],
       [ 5.        ,  6.        , 21.5       ,  8.        ],
       [11.        ,  9.33333333, 13.        , 14.        ]])

In [22]:
data.fillna(data.mean())

A          B     C     D
0  10.0  20.000000  30.0  40.0
1   1.0   2.000000  21.5   4.0
2   5.0   6.000000  21.5   8.0
3  11.0   9.333333  13.0  14.0

In [23]:
df=pd.DataFrame([['Red','L',15.1,'Class1'],['Green','XL',20,'Class2'],['Blue','s',12.34,'Class2'],['Red','M',13,'Class1']],columns=['Color','Size','Price','Classlabel'])
df

Color Size  Price Classlabel
0    Red    L  15.10     Class1
1  Green   XL  20.00     Class2
2   Blue    s  12.34     Class2
3    Red    M  13.00     Class1

In [24]:
#map size as s=1,m=2,l=3,xl=4 using dictionary
d={}


In [25]:
import pandas as pd
Df=pd.read_csv('data1.csv')
Df.isnull().sum()

A    0
B    1
C    2
D    0
dtype: int64

In [26]:
df=pd.read_csv('C:/Users\HP/Documents/2dfd2de0d4f8727f873422c5d959fff5-ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv')
df

PassengerId\tSurvived\tPclass\tName\tSex\tAge\tSibSp\tParch\tTicket\tFare\tCabin\tEmbarked  \
0                                      1\t0\t3\tBraund                                           
1                                     2\t1\t1\tCumings                                           
2                                   3\t1\t3\tHeikkinen                                           
3                                    4\t1\t1\tFutrelle                                           
4                                       5\t0\t3\tAllen                                           
..                                                 ...                                           
151                                   152\t1\t1\tPears                                           
152                                     153\t0\t3\tMeo                                           
153                            154\t0\t3\tvan Billiard                                           
154                                   155\t0\t3\tOlsen                                           
155                                156\t0\t1\tWilliams                                           

                                            Unnamed: 1  
0     Mr. Owen Harris\tmale\t22\t1\t0\tA/5 21171\t7...  
1     Mrs. John Bradley (Florence Briggs Thayer)\tf...  
2     Miss. Laina\tfemale\t26\t0\t0\tSTON/O2. 31012...  
3     Mrs. Jacques Heath (Lily May Peel)\tfemale\t3...  
4     Mr. William Henry\tmale\t35\t0\t0\t373450\t8....  
..                                                 ...  
151   Mrs. Thomas (Edith Wearne)\tfemale\t22\t1\t0\...  
152   Mr. Alfonzo\tmale\t55.5\t0\t0\tA.5. 11206\t8....  
153   Mr. Austin Blyler\tmale\t40.5\t0\t2\tA/5. 851...  
154   Mr. Ole Martin\tmale\t\t0\t0\tFa 265302\t7.31...  
155   Mr. Charles Duane\tmale\t51\t0\t1\tPC 17597\t...  

[156 rows x 2 columns]

In [27]:
df.head(5)


PassengerId\tSurvived\tPclass\tName\tSex\tAge\tSibSp\tParch\tTicket\tFare\tCabin\tEmbarked  \
0                                    1\t0\t3\tBraund                                           
1                                   2\t1\t1\tCumings                                           
2                                 3\t1\t3\tHeikkinen                                           
3                                  4\t1\t1\tFutrelle                                           
4                                     5\t0\t3\tAllen                                           

                                          Unnamed: 1  
0   Mr. Owen Harris\tmale\t22\t1\t0\tA/5 21171\t7...  
1   Mrs. John Bradley (Florence Briggs Thayer)\tf...  
2   Miss. Laina\tfemale\t26\t0\t0\tSTON/O2. 31012...  
3   Mrs. Jacques Heath (Lily May Peel)\tfemale\t3...  
4   Mr. William Henry\tmale\t35\t0\t0\t373450\t8....

In [28]:
df.isnull().sum()

PassengerId\tSurvived\tPclass\tName\tSex\tAge\tSibSp\tParch\tTicket\tFare\tCabin\tEmbarked    0
Unnamed: 1                                                                                    0
dtype: int64

In [29]:
df1=pd.DataFrame([['a','c'],['b','a'],['b','a']],dtype='category')

In [30]:
df1

0  1
0  a  c
1  b  a
2  b  a

In [31]:
#one_hot_encoding
import pandas as pd
df2=pd.DataFrame({
    'name':['joseph','sanju','sanjna','klaus','damon'],
    'country':['russia','germany','india','australia','korea']
})
df2

name    country
0  joseph     russia
1   sanju    germany
2  sanjna      india
3   klaus  australia
4   damon      korea

In [32]:
df2=pd.concat([df2,pd.get_dummies(df2['country'],prefix='country')],axis=1)
df2.drop(['country'],axis=1,inplace=True)
df2

name  country_australia  country_germany  country_india  country_korea  \
0  joseph                  0                0              0              0   
1   sanju                  0                1              0              0   
2  sanjna                  0                0              1              0   
3   klaus                  1                0              0              0   
4   damon                  0                0              0              1   

   country_russia  
0               1  
1               0  
2               0  
3               0  
4               0

In [33]:
from sklearn_pandas import CategoricalImputer
c=CategoricalImputer(missing_values='c')
c.fit_transform(df1[1])

array(['a', 'a', 'a'], dtype=object)

In [5]:
pip install sklearn-pandas

  Using cached https://files.pythonhosted.org/packages/1f/48/4e1461d828baf41d609efaa720d20090ac6ec346b5daad3c88e243e2207e/sklearn_pandas-1.8.0-py2.py3-none-any.whl
Note: you may need to restart the kernel to use updated packages.


In [34]:
from sklearn_pandas import CategoricalImputer
df=pd.DataFrame('a b c c b b b a'.split(),dtype='category')
df

0
0  a
1  b
2  c
3  c
4  b
5  b
6  b
7  a

In [35]:
ci=CategoricalImputer(missing_values=0)
ci.fit_transform(df[0])

array(['a', 'b', 'c', 'c', 'b', 'b', 'b', 'a'], dtype=object)

In [36]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(df)
y

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 1, 2, 2, 1, 1, 1, 0])

In [37]:
le.inverse_transform(y)

array(['a', 'b', 'c', 'c', 'b', 'b', 'b', 'a'], dtype=object)

In [38]:
pd.get_dummies(df,prefix='abc',drop_first=True)


abc_b  abc_c
0      0      0
1      1      0
2      0      1
3      0      1
4      1      0
5      1      0
6      1      0
7      0      0

In [39]:
df[0]=y

In [40]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(categorical_features=[0])
ohe.fit_transform(df).toarray()

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [41]:
d=np.array([1.0,2.0,3.0,4.0,5.0])

In [44]:
d=pd.DataFrame(d)
d

0
0  1.0
1  2.0
2  3.0
3  4.0
4  5.0

In [46]:
#normalisation
def f(x):
    y=x-min(x)/max(x)-min(x)
    return y
d.apply(f)

0
0 -0.2
1  0.8
2  1.8
3  2.8
4  3.8

In [48]:
#standardisation
def s(x):
    y=x-np.mean(x)/np.std(x)
    return y
d.apply(s)

0
0 -1.12132
1 -0.12132
2  0.87868
3  1.87868
4  2.87868

In [50]:
df_wine=pd.read_csv("C:\\Users\\HP\\Downloads\\wine1.csv")

In [52]:
df_wine

1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29   5.64  1.04  \
0    1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
1    1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
2    1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
3    1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
4    1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97   6.75  1.05   
..  ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
172  3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
173  3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
174  3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
175  3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
176  3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

     3.92  1065  
0    3.40  1050  
1    3.17  1185  
2    3.45  1480  
3    2.93   735  
4    2.85  1450  
..    ...   ...  
172  1.74   740  
173  1.56   750  
174  1.56   835  
175  1.62   840  
176  1.60   560  

[177 rows x 14 columns]

In [54]:
df_wine.shapeg

(177, 14)

In [55]:
df_wine.columns='a b c d e f g h i j k l m n'.split()

In [58]:
from sklearn.model_selection import train_test_split
train,test=df_wine.iloc[:,1:],df_wine.iloc[:,0]
x_train,y_train,x_test,y_test=train_test_split(train,test,test_size=0.3)

In [59]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train_std=sc.fit_transform(x_train)
y_train_std=sc.transform(x_train)
x_train_std[:,1]

array([-0.86560739, -0.4955844 , -1.24444045, -1.26206059, -0.01984057,
       -0.63654554, -0.53082469, -0.15199163, -0.40748369, -0.40748369,
       -1.05942895,  1.20475931,  2.38530884,  0.08588029,  0.96688739,
        0.1123105 , -0.6189254 ,  1.786224  ,  0.67615505, -0.24009234,
       -0.53082469, -0.86560739, -0.61011533, -0.53082469, -0.54844483,
       -0.46034412, -1.40302173,  0.61448455, -0.51320455,  0.55281405,
       -0.71583618,  0.61448455, -0.41629377, -0.64535561, -0.73345632,
        0.73782555, -0.17842185,  2.00647578,  1.71574344,  0.57924427,
       -0.46034412, -1.02418867, -0.72464625,  1.5747823 ,  1.46025137,
        1.35453052,  1.50430173,  0.85235647,  1.09022839, -0.39867362,
        2.79938218, -0.4955844 , -0.6189254 ,  1.73336358,  0.30613206,
        1.38977081, -0.31938298, -1.00656853, -0.63654554, -0.53082469,
        0.82592626,  1.2399996 , -0.44272398, -0.38986355, -1.27087066,
       -1.08585917, -0.70702611, -0.58368512, -0.60130526, -0.55

In [61]:
from sklearn.preprocessing import MinMaxScaler
sm=MinMaxScaler()
x_train_nor=sm.fit_transform(x_train)
y_train_nor=sm.transform(y_train)