In [2]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import pandas as pd
from sklearn.datasets import load_iris

In [3]:
df=load_iris()
x=df.data[:,:3]
y=df.target
df

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [67]:
x.shape,y.shape

((150, 3), (150,))

In [68]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=0)

In [69]:
obj=SVC(kernel="linear")
obj.fit(xtrain,ytrain)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [70]:
p=obj.predict(xtest)

In [71]:
p

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 1, 0, 0, 1, 1, 0])

In [72]:
accuracy_score(p,ytest)

0.9666666666666667

In [73]:
confusion_matrix(p,ytest)

array([[11,  0,  0],
       [ 0, 13,  1],
       [ 0,  0,  5]], dtype=int64)

In [74]:
classification_report(p,ytest)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        11\n           1       1.00      0.93      0.96        14\n           2       0.83      1.00      0.91         5\n\n    accuracy                           0.97        30\n   macro avg       0.94      0.98      0.96        30\nweighted avg       0.97      0.97      0.97        30\n'

In [75]:
obj1=SVC(kernel="rbf",gamma=0.5)
obj1.fit(xtrain,ytrain)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.5, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [76]:
p1=obj.predict(xtest)
p1

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 1, 0, 0, 1, 1, 0])

In [77]:
accuracy_score(p1,ytest)

0.9666666666666667

In [78]:
confusion_matrix(p1,ytest)

array([[11,  0,  0],
       [ 0, 13,  1],
       [ 0,  0,  5]], dtype=int64)

In [79]:
classification_report(p1,ytest)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        11\n           1       1.00      0.93      0.96        14\n           2       0.83      1.00      0.91         5\n\n    accuracy                           0.97        30\n   macro avg       0.94      0.98      0.96        30\nweighted avg       0.97      0.97      0.97        30\n'

In [80]:
obj2=SVC(kernel="poly",degree=5)
obj1.fit(xtrain,ytrain)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.5, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [81]:
p2=obj.predict(xtest)
p2

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 1, 0, 0, 1, 1, 0])

In [82]:
accuracy_score(p2,ytest)

0.9666666666666667

In [83]:
confusion_matrix(p2,ytest)

array([[11,  0,  0],
       [ 0, 13,  1],
       [ 0,  0,  5]], dtype=int64)

In [84]:
classification_report(p2,ytest)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        11\n           1       1.00      0.93      0.96        14\n           2       0.83      1.00      0.91         5\n\n    accuracy                           0.97        30\n   macro avg       0.94      0.98      0.96        30\nweighted avg       0.97      0.97      0.97        30\n'

In [85]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [86]:
df1=pd.read_csv("C:\\Users\\HP\\Downloads\\balance-scale.csv")

In [87]:
df1

B  1  1.1  1.2  1.3
0    R  1    1    1    2
1    R  1    1    1    3
2    R  1    1    1    4
3    R  1    1    1    5
4    R  1    1    2    1
..  .. ..  ...  ...  ...
619  L  5    5    5    1
620  L  5    5    5    2
621  L  5    5    5    3
622  L  5    5    5    4
623  B  5    5    5    5

[624 rows x 5 columns]

In [88]:
X=df1.iloc[:,1:]
Y=df1.iloc[:,0]

In [89]:
X.shape,Y.shape

((624, 4), (624,))

In [90]:
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=0.30,random_state=0)

In [91]:
xtrain.shape,xtest.shape

((436, 4), (188, 4))

In [92]:
gini=DecisionTreeClassifier(criterion='gini',max_depth=3,min_samples_leaf=5)
gini.fit(xtrain,ytrain)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [93]:
pre=gini.predict(xtest)
pre

array(['L', 'L', 'L', 'R', 'L', 'L', 'L', 'L', 'L', 'R', 'R', 'R', 'R',
       'L', 'R', 'L', 'R', 'L', 'R', 'L', 'L', 'R', 'R', 'R', 'R', 'L',
       'L', 'L', 'R', 'R', 'L', 'R', 'L', 'L', 'R', 'L', 'R', 'L', 'L',
       'L', 'L', 'R', 'R', 'L', 'L', 'L', 'L', 'R', 'R', 'R', 'R', 'R',
       'R', 'L', 'L', 'R', 'R', 'L', 'L', 'R', 'L', 'L', 'L', 'R', 'R',
       'R', 'R', 'L', 'R', 'R', 'R', 'R', 'R', 'R', 'L', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'L', 'R', 'L', 'L', 'R', 'R', 'L', 'L',
       'L', 'R', 'R', 'R', 'R', 'L', 'L', 'R', 'R', 'R', 'R', 'L', 'L',
       'L', 'R', 'R', 'L', 'R', 'L', 'R', 'L', 'L', 'L', 'R', 'R', 'L',
       'R', 'L', 'R', 'L', 'R', 'R', 'L', 'R', 'L', 'R', 'R', 'L', 'L',
       'L', 'R', 'L', 'R', 'R', 'R', 'R', 'R', 'R', 'L', 'R', 'R', 'R',
       'L', 'R', 'R', 'L', 'L', 'R', 'R', 'R', 'R', 'L', 'R', 'R', 'L',
       'L', 'L', 'L', 'L', 'L', 'R', 'R', 'R', 'L', 'L', 'L', 'R', 'L',
       'R', 'L', 'R', 'L', 'L', 'R', 'L', 'L', 'R', 'L', 'L', 'L

In [97]:
accuracy_score(pre,ytest)

0.75

In [98]:
confusion_matrix(pre,ytest)

array([[ 0, 15,  9],
       [ 7, 72,  7],
       [ 6,  3, 69]], dtype=int64)

In [99]:
classification_report(pre,ytest)

'              precision    recall  f1-score   support\n\n           B       0.00      0.00      0.00        24\n           L       0.80      0.84      0.82        86\n           R       0.81      0.88      0.85        78\n\n    accuracy                           0.75       188\n   macro avg       0.54      0.57      0.55       188\nweighted avg       0.70      0.75      0.73       188\n'

In [94]:
entropy=DecisionTreeClassifier(criterion='entropy')
entropy.fit(xtrain,ytrain)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [96]:
pre1=entropy.predict(xtest)
pre1

array(['L', 'L', 'L', 'R', 'L', 'B', 'B', 'L', 'L', 'R', 'L', 'R', 'B',
       'R', 'L', 'L', 'R', 'L', 'R', 'L', 'L', 'R', 'R', 'B', 'L', 'L',
       'B', 'L', 'R', 'L', 'B', 'L', 'L', 'B', 'R', 'B', 'R', 'B', 'L',
       'R', 'L', 'R', 'L', 'L', 'L', 'L', 'L', 'R', 'R', 'R', 'R', 'R',
       'B', 'R', 'L', 'R', 'R', 'L', 'L', 'B', 'L', 'R', 'L', 'B', 'L',
       'R', 'R', 'L', 'R', 'R', 'B', 'R', 'R', 'R', 'B', 'R', 'R', 'L',
       'R', 'R', 'R', 'R', 'L', 'B', 'L', 'R', 'L', 'L', 'B', 'L', 'L',
       'L', 'B', 'R', 'R', 'L', 'L', 'L', 'R', 'R', 'R', 'L', 'L', 'R',
       'L', 'R', 'R', 'L', 'R', 'B', 'L', 'L', 'L', 'R', 'L', 'R', 'L',
       'R', 'R', 'R', 'L', 'R', 'L', 'B', 'R', 'L', 'B', 'R', 'L', 'L',
       'L', 'R', 'R', 'R', 'R', 'R', 'R', 'L', 'R', 'L', 'R', 'R', 'L',
       'L', 'R', 'R', 'L', 'L', 'R', 'R', 'B', 'R', 'R', 'R', 'R', 'B',
       'L', 'L', 'L', 'L', 'L', 'R', 'L', 'L', 'L', 'L', 'R', 'L', 'L',
       'B', 'L', 'R', 'L', 'L', 'R', 'R', 'L', 'R', 'L', 'L', 'L