In [1]:
import numpy as np
import pandas as pd

In [2]:
F= [
   [10,20,30,40],
   [1.0,2.0,np.nan,4.0],
   [5.0,6.0,np.nan,8.0],
   [0.0,11.0,12.0,np.nan]]

In [3]:
X = pd.DataFrame(F,columns=['A','B','C','D'])

In [4]:
X.head(2)

A     B     C     D
0  10.0  20.0  30.0  40.0
1   1.0   2.0   NaN   4.0

In [5]:
X.tail(2)

A     B     C    D
2  5.0   6.0   NaN  8.0
3  0.0  11.0  12.0  NaN

In [6]:
X.values

array([[10., 20., 30., 40.],
       [ 1.,  2., nan,  4.],
       [ 5.,  6., nan,  8.],
       [ 0., 11., 12., nan]])

In [7]:
X.isna().sum()

A    0
B    0
C    2
D    1
dtype: int64

In [8]:
X.to_numpy()

array([[10., 20., 30., 40.],
       [ 1.,  2., nan,  4.],
       [ 5.,  6., nan,  8.],
       [ 0., 11., 12., nan]])

In [9]:
from io import StringIO
data = '''A,B,C,D
          1,2,3, 
          5,6,,7
          8,9,,'''

In [10]:
D = pd.read_csv(StringIO(data))

In [26]:
X

A     B     C     D
0  10.0  20.0  30.0  40.0
1   1.0   2.0   NaN   4.0
2   5.0   6.0   NaN   8.0
3   0.0  11.0  12.0   NaN

In [29]:
X.dropna(axis=1)

A     B
0  10.0  20.0
1   1.0   2.0
2   5.0   6.0
3   0.0  11.0

In [25]:
X.dropna(axis=0)

A     B     C     D
0  10.0  20.0  30.0  40.0

In [30]:
X['C'].dropna()

0    30.0
3    12.0
Name: C, dtype: float64

In [33]:
X.dropna(how='all')

A     B     C     D
0  10.0  20.0  30.0  40.0
1   1.0   2.0   NaN   4.0
2   5.0   6.0   NaN   8.0
3   0.0  11.0  12.0   NaN

In [36]:
X.dropna(thresh=3,axis=1)

A     B     D
0  10.0  20.0  40.0
1   1.0   2.0   4.0
2   5.0   6.0   8.0
3   0.0  11.0   NaN

In [37]:
X.dropna(subset=['C'],axis=0)

A     B     C     D
0  10.0  20.0  30.0  40.0
3   0.0  11.0  12.0   NaN

In [38]:
X

A     B     C     D
0  10.0  20.0  30.0  40.0
1   1.0   2.0   NaN   4.0
2   5.0   6.0   NaN   8.0
3   0.0  11.0  12.0   NaN

In [39]:
from sklearn.impute import SimpleImputer 

In [42]:
sim = SimpleImputer(strategy='most_frequent',missing_values=np.nan)

In [43]:
sim.fit_transform(X)

array([[10., 20., 30., 40.],
       [ 1.,  2., 12.,  4.],
       [ 5.,  6., 12.,  8.],
       [ 0., 11., 12.,  4.]])

In [44]:
df = pd.DataFrame([[-1,9,8,7],
                  [2,3,-1,4],
                  [5,7,-1,-1]])

In [48]:
sim1 = SimpleImputer(strategy='median',missing_values=-1)

In [49]:
sim1.fit_transform(df)

array([[3.5, 9. , 8. , 7. ],
       [2. , 3. , 8. , 4. ],
       [5. , 7. , 8. , 5.5]])

# TAsk 2


In [55]:
data1 = [['Red','L',15.1,'Class1'],
        ['Green','XL',20,'Class2'],
        ['Blue','S',12.34,'Class2'],
        ['Red','M',13,'Class1'],]

In [56]:
data1 = pd.DataFrame(data1,columns=['Color','Size','Price','ClassLabel'])

In [57]:
data1

Color Size  Price ClassLabel
0    Red    L  15.10     Class1
1  Green   XL  20.00     Class2
2   Blue    S  12.34     Class2
3    Red    M  13.00     Class1

In [67]:
cl={'Class1':1,'Class2':2}
d={'L':1,'XL':4,'S':1,'M':2}

In [65]:
data1['Size']=data1['Size'].map(d)

In [68]:
data1['ClassLabel']=data1['ClassLabel'].map(cl)

In [69]:
data1

Color  Size  Price  ClassLabel
0    Red     1  15.10           1
1  Green     4  20.00           2
2   Blue     1  12.34           2
3    Red     2  13.00           1