In [1]:
import numpy as np
l=[32.5, 40.32, 43.56, 44.67,49.5]
c=np.array(l)
o=c*9/5+32


In [2]:
np.array([[3,4,5],[4,5,6],[8,9,0]])

array([[3, 4, 5],
       [4, 5, 6],
       [8, 9, 0]])

In [3]:
np.array([[3,4,5,6],[4,6,7,3],[3,1,3,4]])

array([[3, 4, 5, 6],
       [4, 6, 7, 3],
       [3, 1, 3, 4]])

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,11,2)


array([ 0,  2,  4,  6,  8, 10])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.ones(3)

array([1., 1., 1.])

In [8]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [9]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [12]:
import random
random.randint(1,10)

8

In [13]:
np.random.rand(2)    #range from 0 to 1, arugument will number of prints

array([0.70252121, 0.47509023])

In [14]:
np.random.randn(2,2)#include negative numbers 

array([[ 0.00873974,  0.78932104],
       [-1.18067139,  0.79104739]])

In [15]:
np.random.randint(1,100,10) #start,end,no. of prints

array([68, 43,  9, 61, 44, 87, 44, 24, 74, 50])

In [16]:
tan=np.arange(9).reshape(3,3)
tan

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
o.max()

121.1

In [18]:
o.min()


90.5

In [19]:
o.shape


(5,)

In [20]:
o.dtype

dtype('float64')

In [21]:
s=np.arange(9)
s


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
s[4]

4

In [53]:
s[4:6]

array([4, 5])

In [58]:
#broadcasting
s[:6]=100

In [57]:
s

array([100, 100, 100, 100, 100, 100,   6,   7,   8])

In [63]:
tan

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
tan[0]

array([0, 1, 2])

In [65]:
tan[0,0]

0

In [83]:
tan[1:3,1:2]#2d indexing

array([[4],
       [7]])

In [ ]:
#selection

In [85]:
s>55

array([ True,  True,  True,  True,  True,  True, False, False, False])