In [50]:
import numpy as np
arr=np.arange(0,10)

In [51]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [53]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [55]:
arr/arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [56]:
arr%arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in remainder
  """Entry point for launching an IPython kernel.


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [57]:
np.sqrt(arr)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [58]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [59]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [60]:
np.log(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [61]:
# pandas library
# adv version of excel, 
# series,dataframe,joining,input\output


In [62]:
#creating a Series
import pandas as pd
my_list=[10,20,30]


pd.Series(data=my_list,index=[1,2,3])

1    10
2    20
3    30
dtype: int64

In [63]:
label=['a','b','c']
pd.Series(data=label)

0    a
1    b
2    c
dtype: object

In [64]:
pd.Series(arr)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [65]:
pd.Series(label,my_list)

10    a
20    b
30    c
dtype: object

In [66]:
ser2=pd.Series([1,2,3,4,5],index=['USA','Germany','japan','india','Italy'])

In [67]:
ser2

USA        1
Germany    2
japan      3
india      4
Italy      5
dtype: int64

In [68]:
ser2['USA']

1

In [69]:
ser1=pd.Series([1,2,3,4,5],index=['USA','Germany','japan','Arbia','Italy'])

In [70]:
ser1

USA        1
Germany    2
japan      3
Arbia      4
Italy      5
dtype: int64

In [71]:
ser1+ser2

Arbia       NaN
Germany     4.0
Italy      10.0
USA         2.0
india       NaN
japan       6.0
dtype: float64

In [72]:
#DataFrames
fr=np.random.randn(5,4)


In [91]:
pd.DataFrame(fr)

0         1         2         3
0  0.927451 -2.271513  0.080613  2.053863
1 -1.270800  1.441709  0.430555  0.222428
2  0.714529  0.112825  1.525678 -0.838832
3 -1.416186 -0.706970 -1.356477  0.426369
4  0.335478  0.291301  0.025917  2.010036

In [92]:
from numpy.random import randn
df=pd.DataFrame(randn(5,4),index=['A' ,'B', 'C' ,'D', 'E'],columns=['W' ,'X', 'Y', 'Z'])

In [93]:
df

W         X         Y         Z
A  1.293777  0.947988  0.504610  1.216923
B  1.825052  0.595347  0.293960  1.241440
C  0.681073 -0.817966 -0.115558  1.715163
D  0.620822  1.228849  0.352730  0.963445
E  0.733544 -0.831647  0.429671  0.939162

In [94]:
df[['W','Y']]

W         Y
A  1.293777  0.504610
B  1.825052  0.293960
C  0.681073 -0.115558
D  0.620822  0.352730
E  0.733544  0.429671

In [95]:
df.W

A    1.293777
B    1.825052
C    0.681073
D    0.620822
E    0.733544
Name: W, dtype: float64

In [96]:
df['newCol']=df['W']+df['Y']#adding column

In [97]:
df

W         X         Y         Z    newCol
A  1.293777  0.947988  0.504610  1.216923  1.798387
B  1.825052  0.595347  0.293960  1.241440  2.119011
C  0.681073 -0.817966 -0.115558  1.715163  0.565514
D  0.620822  1.228849  0.352730  0.963445  0.973551
E  0.733544 -0.831647  0.429671  0.939162  1.163215

In [98]:
df.drop('W',axis=1)#deleting column

X         Y         Z    newCol
A  0.947988  0.504610  1.216923  1.798387
B  0.595347  0.293960  1.241440  2.119011
C -0.817966 -0.115558  1.715163  0.565514
D  1.228849  0.352730  0.963445  0.973551
E -0.831647  0.429671  0.939162  1.163215

In [99]:
df

W         X         Y         Z    newCol
A  1.293777  0.947988  0.504610  1.216923  1.798387
B  1.825052  0.595347  0.293960  1.241440  2.119011
C  0.681073 -0.817966 -0.115558  1.715163  0.565514
D  0.620822  1.228849  0.352730  0.963445  0.973551
E  0.733544 -0.831647  0.429671  0.939162  1.163215

In [100]:
df.drop('W',axis=1,inplace=True)#inplace will change df from memory

In [89]:
df

X         Y         Z    newCol
A -0.204774  1.512162  0.913468  2.529985
B -1.203199 -0.990531 -0.700981  1.034567
C  0.361193 -1.164359 -0.019715 -0.794009
D -0.721654 -2.578322  3.151781 -4.471614
E -0.987704 -1.211279 -0.864639 -0.532193

In [101]:
df.drop('E',axis=0)

X         Y         Z    newCol
A  0.947988  0.504610  1.216923  1.798387
B  0.595347  0.293960  1.241440  2.119011
C -0.817966 -0.115558  1.715163  0.565514
D  1.228849  0.352730  0.963445  0.973551

In [102]:
df.loc['A']

X         0.947988
Y         0.504610
Z         1.216923
newCol    1.798387
Name: A, dtype: float64

In [108]:
df.loc[['A','B'],['Y','Z']]# w as argument will give error as w is removed from memory using inplace

Y         Z
A  0.50461  1.216923
B  0.29396  1.241440

In [114]:
#condition Selection
df>0

X      Y     Z  newCol
A   True   True  True    True
B   True   True  True    True
C  False  False  True    True
D   True   True  True    True
E  False   True  True    True

In [115]:
df[df>0]# will show the values

X         Y         Z    newCol
A  0.947988  0.504610  1.216923  1.798387
B  0.595347  0.293960  1.241440  2.119011
C       NaN       NaN  1.715163  0.565514
D  1.228849  0.352730  0.963445  0.973551
E       NaN  0.429671  0.939162  1.163215

In [122]:
df[df['X']>0]['Y']#will remove nan value  row 

A    0.50461
B    0.29396
D    0.35273
Name: Y, dtype: float64

In [121]:
df[df['X']>0]# will remove every row with NaN values

X        Y         Z    newCol
A  0.947988  0.50461  1.216923  1.798387
B  0.595347  0.29396  1.241440  2.119011
D  1.228849  0.35273  0.963445  0.973551

In [125]:
df[df['X']>0][['Y','Z']]

Y         Z
A  0.50461  1.216923
B  0.29396  1.241440
D  0.35273  0.963445